source "https://rubygems.org"

group :test, :development do
  gem "pry"
  gem "rspec", "~> 3.7"
  gem "capybara", "~> 2.15"
  gem "launchy"

end

    gem "sinatra", "~> 2.0"
    gem "sinatra-contrib"
    gem "rake"
